services:
  - type: web
    name: restaurant-app
    env: python
    buildCommand: pip install -r server/requirements.txt && cd client && npm install && npm run build
    startCommand: gunicorn --chdir server wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true