services:
  - type: web
    name: restaurant-app
    env: python
    buildCommand: | 
      cd client && npm install && npm run build 
      cd ../server && pip install -r requirements.txt
      startCommand: cd server && gunicorn wsgi:app --bind 0.0.0.0:$PORT
      envVars:
        - key: SECRET_KEY
          generateValue: true